[package]
name = "bfdbg"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }

[[bin]]
name = "bfdbg"
path = "src/main.rs"
